# Generated by Django 3.1.7 on 2021-03-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_auto_20210314_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='age',
        ),
    ]
